# Generated by Django 4.2.11 on 2024-03-12 07:17

import app1.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='my_file',
            field=models.ImageField(default='null', upload_to='img', validators=[app1.validator.validate_file_extension]),
        ),
    ]
