# Generated by Django 4.2.11 on 2024-03-14 09:08

import app1.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_photo_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.AlterField(
            model_name='photo',
            name='my_file',
            field=models.ImageField(default='null', upload_to='img/<django.db.models.fields.DateField>', validators=[app1.validator.validate_file_extension]),
        ),
    ]
