# Generated by Django 4.2.11 on 2024-03-14 09:19

import app1.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delete_goods_alter_photo_my_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='my_file',
            field=models.ImageField(default='null', upload_to='img/20240314', validators=[app1.validator.validate_file_extension]),
        ),
    ]
