# Generated by Django 4.2.11 on 2024-03-15 01:55

import app1.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_photo_my_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='my_file',
        ),
        migrations.AddField(
            model_name='photo',
            name='new_image',
            field=models.ImageField(default='null', upload_to='img/20240315', validators=[app1.validator.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='photo',
            name='raw_image',
            field=models.ImageField(default='null', upload_to='img/20240315', validators=[app1.validator.validate_file_extension]),
        ),
    ]
