# Generated by Django 4.2.11 on 2024-03-27 05:56

import app1.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_photo_extension_alter_photo_new_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('extension', models.CharField(max_length=7)),
                ('date', models.DateField(auto_now_add=True)),
                ('pre_image', models.ImageField(default='null', upload_to='img/20240327', validators=[app1.validator.validate_file_extension])),
                ('tar_image', models.ImageField(default='null', upload_to='img/20240327', validators=[app1.validator.validate_file_extension])),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
