# Generated by Django 4.2.11 on 2024-03-28 03:41

import app1.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_medical_delete_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='pre_image',
        ),
        migrations.RemoveField(
            model_name='medical',
            name='tar_image',
        ),
        migrations.AddField(
            model_name='medical',
            name='pre_img',
            field=models.ImageField(default='null', upload_to='img/20240328', validators=[app1.validator.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='medical',
            name='tar_img',
            field=models.ImageField(default='null', upload_to='img/20240328', validators=[app1.validator.validate_file_extension]),
        ),
    ]
