# Generated by Django 4.2.11 on 2024-03-28 04:58

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_medical_extension_remove_medical_pre_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='raw_file',
            field=models.FileField(default='null', upload_to=app1.models.upload_to),
        ),
        migrations.AlterField(
            model_name='medical',
            name='pre_img',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='medical',
            name='tar_img',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
